### ISSUE TITLE
Improve `jumpForce` formula

### ISSUE THREAD

**Issue by TechnicJelle** [MythicalSora/Project-Lift-Off#31]
In dd4ac89de9923f6e1d080c00f13585e7ec3dcb00 and e70c596de43cc9538dd1c3b9ff3bdb22afca6c97, I've implemented that when you hold the jump button, the player jumps a bit higher! The double jumping also works nicely with this.

There is an improvement that can be made to it, though:
Currently, the jump force is being calculated based on the amount of time (in milliseconds) that the jump has been going on for, represented by the `jumpProgress` value.
That progress is then _linearly_ remapped to a jump force amount.
This works, but it doesn't feel quite right.

**Therefore, I feel like it would be a good idea to construct a better formula to transform the `jumpProgress` to the `jumpForce`.**

`jumpProgress` (range: `0..1`) represents how long the jump has been going on for.
`0.0f`: when the jump has just started (and thus when the `jumpForce` should be at its maximum (which is `MAX_GRADUAL_JUMP_FORCE`))
`1.0f`: when the jump has reached its maximum height (and this when the `jumpForce` should be 0)

`jumpForce` (range: `MAX_GRADUAL_JUMP_FORCE..0`) is the value that gets passed to the `ApplyForce()` method.

**Comment by TechnicJelle** [comment]
The red line is what we have right now and the white line is what we want to achieve
![Animation](https://user-images.githubusercontent.com/22576047/153449008-d5662e17-36a2-4af8-b5c9-fd43981fe0c1.gif)
^ Preferably with nice control over the exact properties of the curve, like the GIF shows

**Comment by MythicalSora** [comment]
@Adecazenove No implementation has been made, so I'm guessing it stays open :' )
