### ISSUE TITLE
[8] Player character animations

### ISSUE THREAD

**Issue by Adecazenove** [MythicalSora/Project-Lift-Off#34]
- [x] run
- [x] attack
- [ ] upwards attack
- [ ] downwards attack
- [x] jump
- [x] dash
- [ ] (GXP) hit animation
- [ ] (optional) Wall climbing
- [ ] (optional) Death

**Comment by Nomaaaaad** [comment]
![sprite_sheet_demo3](https://user-images.githubusercontent.com/94765904/154496249-97d44bfb-f33c-4b67-bac2-232bc53fb202.png)
