### ISSUE TITLE
[2] Implement visual assets

### ISSUE THREAD

**Issue by Adecazenove** [MythicalSora/Project-Lift-Off#38]
- [x] implement enemy assets
- [x] implement player assets
- [ ] implement animations
- [x] implement level visuals

**Comment by TechnicJelle** [comment]
List of animations that have been implemented:
**Player:**
- Idle
- Dash (ish (`isDashing` variable is not good))
- Run
- Jump
- Slash (broken: it's in there, but it only plays the first frame)

**Drone:**
- Idle/Flying
- Explosion

**Turret:**
- Idle/Looking
- Explosion (but doesn't take the mirroredness into account, so the explosion side is wrong sometimes, but it goes quick enough to be barely noticable on a quick glance)

**Walker:**
- Walking
- Explosion


All in all, I think that's enough to call this issue closed as well.
